### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by jingxuanlim** [Octoframes/jupyter_capture_output#1]
Hello. I was looking for a solution to export my jupyter cells and arrived at this repo from [here](https://discourse.jupyter.org/t/cell-magic-to-save-image-output-as-a-png-file/11906/10).

Would love to give this a shot, but ran into some installation problems.

```
$ pip install jupyter_capture_output
ERROR: Could not find a version that satisfies the requirement jupyter_capture_output (from versions: none)
ERROR: No matching distribution found for jupyter_capture_output
```

Appreciate any help/suggestions. Thanks!

**Comment by kolibril13** [comment]
Hello @jingxlim,
thanks for the report!
This package only runs with a python version >=3.8.
Are you maybe on python 3.7 or 3.6 ?

**Comment by jingxuanlim** [comment]
Hi @kolibril13. Yes, you are right -- I am on 3.6.

I was able to install it in a different env though! Thanks for the tip!

By the way, does `jupyter-capture-output` only work for matplotlib plots? I tried it on some `print` statements but it didn't work.

**Comment by kolibril13** [comment]
Nice!
I'll update the README accordingly.
Right now, only png images are captured, no matter if they come from matplotlib, manim or PIL etc. [(See here)](https://github.com/kolibril13/jupyter-capture-output/blob/fc2a3bf71c10334f1229c8f8c8bde5ee7e278179/jupyter_capture_output/co_cellmagic.py#L39). But in future it would be nice to have also implementations to capture text, SVGs or even video output!

**Comment by jingxuanlim** [comment]
Got it. Yeah, that would be great! A viable solution to exporting just some parts of the notebook -- that I understand is not possible with the vanilla export function -- would be great! Keep up the good work!

**Comment by kolibril13** [comment]
I'll see if I find the time to implement these features, and thanks for your appreciation!
I am closing this issue now.
